
# May be overwritten in .github/actions/hugo.yml 
# when deploying to gh pages
baseURL = 'https://qgis.org/'
languageCode = 'en-us'
title = 'QGIS Web Site'
theme = 'qgis'

# This will cause html in markdown files to be rendered directly
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# See https://gohugo.io/content-management/menus/
[menu]
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -110
  
[[menu.main]]
  name = "Community"
  url = "/community/"
  weight = -110 # Sets the menu order 

[[menu.main]]
  name = "Resources"
  url = "/hub/"
  weight = -110 # Sets the menu order 

[[menu.main]]
  name = "Downloads"
  url = "/downloads/"
  weight = -110 # Sets the menu order 

[[menu.main]]
  name = "Value"
  url = "/value-proposition/"
  weight = -110 # Sets the menu order 


# Submenus are done this way: parent -> identifier
[[menu.main]]
  parent = "Downloads"
  name = "Windows"
  url = "/download-windows/"
  weight = -120

[[menu.main]]
  parent = "Downloads"
  name = "macOS"
  url = "/download-mac/"
  weight = -120  

[[menu.main]]
  parent = "Downloads"
  name = "Linux"
  url = "/download-linux/"
  weight = -120  

