baseURL = 'https://qgis.org/'
languageCode = 'en-us'
title = 'QGIS Web Site'
theme = 'qgis'

# This will cause html in markdown files to be rendered directly
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'Community'
  url = '/community/'
  weight = 20
 
# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "QGIS Plugins"
  url = "https://plugins.qgis.org/"
